# Generated by Django 5.2.5 on 2025-12-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date_of_purchased',
            new_name='date_of_purchase',
        ),
    ]
